### ISSUE TITLE
Error Starting Last Docker Image

### ISSUE THREAD

**Issue by jos1264** [qdm12/cloudflare-dns-server#18]
Hi,

I don't know if it's just my case.

The image works correctly, but at the moment I add the variable BLOCK_NSA = on it does not work.

The following error appears with the docker logs "container" command

Thank you.

----------------------
Running as nonrootuser
Unbound version: 1.9.4
Unbound DNS server: cloudflare, quad9
Unbound listening UDP port: 53
Caching is on
Verbosity level set to 1 on 5
Verbosity details level set to 0 on 4
Malicious hostnames and ips blocking is on
44398 malicious hostnames and 177354 malicious IP addresses blacklisted
NSA hostnames blocking is on
8146 NSA hostnames blacklisted
Unbound private addresses: 127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,::1/128,fc00::/7,fe80::/10,::ffff: 0: 0/96
blocks-malicious.conf: 446: error: newline inside quoted string, no end "
blocks-malicious.conf: 447: error: stray '"'
blocks-malicious.conf: 447: error: unknown keyword 'static'
blocks-malicious.conf: 448: error: syntax error
read unbound.conf failed: 4 errors in configuration file
[1573485253] unbound [53: 0] fatal error: Could not read config file: unbound.conf. Maybe try unbound -dd, it stays on the commandline to see more errors, or unbound-checkconf

**Comment by qdm12** [comment]
I had the error yesterday, it was probably an error in the [list of hostnames/IPs generated](https://github.com/qdm12/updated/tree/master/files). I re-generated the files and rebuilt the image, I think you can now `docker pull qmcgaw/cloudflare-dns-server` and try again, it should be working.

I am also in the process of adding a finer grain control over block lists, that's why I'm breaking a few things 😕

**Comment by jos1264** [comment]
It's ok i will try later.

thank you very much.
