### ISSUE TITLE
Unsigned issue when building trust

### ISSUE THREAD

**Issue by TachyonRSA** [qdm12/cloudflare-dns-server#22]
I was just checking the logs of the docker container and it is spammed with

> DS got unsigned CNAME answer from 1.0.0.1 and 1.0.0.1 for DS is-cf.cloudflareresolve.com. while building chain of trust

Then later on the same happens for 1.1.1.1

> S got unsigned CNAME answer from 1.1.1.1 and 1.0.0.1 for DS is-cf.cloudflareresolve.com. while building chain of trust

Any idea on how to resolve this? I assume it is leading to DoT not working.

**Comment by qdm12** [comment]
There are both 1.1.1.1 and 1.0.0.1 as the former is used as a backup DNS when the first fails.

This issue seems related to https://1.1.1.1/help using DNSSEC. From what I've understood, https://1.1.1.1/help uses the hostname is-cf.cloudflareresolve.com which is not exposed on the Internet and therefore the DNSSEC validation fails. There is an issue on that since October 2019 [here](https://community.cloudflare.com/t/cloudflare-dot-and-dnssec/118414/16). I may add an option to disable DNSSEC to test what happens on the help page although it should be kept enabled for better security otherwise.

**Comment by TachyonRSA** [comment]
Ah okay, so the issue only happens when visiting 1.1.1.1/help. Thank you :)
