### ISSUE TITLE
Non-existent domain

### ISSUE THREAD

**Issue by woncheol-kim** [qdm12/cloudflare-dns-server#43]
Hi, I've just tried this docker image and it works good, except one issue:

nslookup clien.net says it's Non-existent domain.

This is unacceptable, although I like the ad-block option of the docker image, because clien.net is one of the Web-sites that I visit daily.

Thanks in advance.

**Comment by qdm12** [comment]
Try setting it with the UNBLOCK environment variable? it's probably blocked due to the block lists. Let me know if that doesn't work.

**Comment by woncheol-kim** [comment]
Wow, that solved the problem. Thanks!
But what if the site is really attacked? Trust my web browser and firewall?

**Comment by qdm12** [comment]
Oh it just came from one of the block lists my program gathers (qdm12/updated).

I have no clue why but that's usually because some malicious activity was detected from that website.

If you've blocked ads too, then it's likely because it got classified as a source of ads.

You can dig through the files in qdm12/files (another repository) if you are curious, but I also happily live with a bunch of domains in UNBLOCK without knowing the exact reason of their blocking 😄
